### ISSUE TITLE
403 error on the demo page

### ISSUE THREAD

**Issue by Naereen** [hakimel/forkit.js#12]
Hi.

First, thanks and bravo, I used forkit.js for a couple of years and.. I love it!

The [demo page](http://lab.hakim.se/forkit-js/) at lab.hakim.se/forkit-js/ is failing with a 403 error, and the old link I had http://hakim.se/lab/forkit.js is dead too.
Could you bring it up back online plz?

Thanks in advance.

**Comment by hakimel** [comment]
Hey. Was changing servers, should be working again now.

**Comment by Naereen** [comment]
Thanks :+1: !
